config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/suits/owner', to: 'suits#owner_index', as: 'owner_index'

  resources :suits do
    resources :rentings, only: [:create]
  end

  resources :rentings, only: [:index, :show, :destroy, :update] do
    resources :reviews, only: [:create]
    resources :messages, only:[:create, :show]
  end

  resources :reviews, only: [:show, :destroy]
end

app/models/suit.rb
class Suit < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :rentings
  has_many :reviews, through: :rentings

  validates :name, presence: true
  validates :color, presence: true
  validates :size, presence: true
  validates :price_per_day, presence: true
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/suits_controller.rb
class SuitsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_suit, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @suits = policy_scope(Suit).near(params[:query], 100)
    else
      @suits = policy_scope(Suit).order(created_at: :desc).where.not(latitude: nil, longitude: nil)
    end

    search_style
    search_size
    search_color


    @markers = @suits.map do |suit|
      {
        lat: suit.latitude,
        lng: suit.longitude,
        infoWindow: { content: render_to_string(partial: "/suits/map_box", locals: { suit: suit }) }
      }
    end
  end

  def show
    @renting = Renting.new
    @renting.suit = @suit
    @rentings = Renting.where(suit_id: @suit.id)
    @reviews = Review.all
    @rentings_dates = @rentings.map do |renting|
      {
        from: renting.start_date,
        to: renting.end_date
      }
    end
    authorize @suit
    @markers =[
      {
        lat: @suit.latitude,
        lng: @suit.longitude#,
        # infoWindow: { content: render_to_string(partial: "/suits/map_box", locals: { suit: suit }) }
      }]
  end

  def new
    @suit = Suit.new
    authorize @suit
  end

  def create
    @suit = Suit.new(suit_params)
    @suit.user_id = current_user.id
    authorize @suit
    if @suit.save
      redirect_to owner_index_path(@suit)
    else
      render :new
    end
  end

  def edit
    authorize @suit
  end

  def update
    @suit.update!(suit_params)
    redirect_to suit_path(@suit)
    authorize @suit
  end

  def destroy
    @suit.destroy!
    redirect_to owner_index_path
    authorize @suit
  end

  def owner_index
    # @suits = Suit.where(user_id: current_user)
    @suits = policy_scope(Suit).where(user_id: current_user)
  end

  private

  def suit_params
    params.require(:suit).permit(:color, :description, :style, :size, :name, :photo, :price_per_day, :address)
  end

  def set_suit
    @suit = Suit.find(params[:id])
  end

  def search_style
    if params[:style].present? && params[:style][:style_selector] != ""
      @suits = policy_scope(Suit).order(created_at: :desc).where.not(latitude: nil, longitude: nil).where(style: params[:style][:style_selector])
    end
  end

  def search_color
    if params[:color].present? && params[:color][:color_selector] != ""
      @suits = policy_scope(Suit).order(created_at: :desc).where.not(latitude: nil, longitude: nil).where(color: params[:color][:color_selector])
    end
  end

  def search_size
    if params[:size].present? && params[:size][:size_selector] != ""
      @suits = policy_scope(Suit).order(created_at: :desc).where.not(latitude: nil, longitude: nil).where(size: params[:size][:size_selector])
    end
  end
end

app/views/suits/_form_suit.html.erb
<div style="font-weight: lighter; font-size: 16px; margin: 70px 0;" class='material-fake'>
  <%= simple_form_for @suit,
  wrapper: :horizontal_form,
  wrapper_mappings: {
    boolean:       :horizontal_boolean,
    check_boxes:   :horizontal_collection,
    date:          :horizontal_multi_select,
    datetime:      :horizontal_multi_select,
    file:          :horizontal_file,
    radio_buttons: :horizontal_collection,
    range:         :horizontal_range,
    time:          :horizontal_multi_select
  } do |f| %>
    <%= f.input :name, label: false, placeholder: 'Name your suit' %>
    <%= f.input :color, label: false, collection: ["Blue", "Black", "Red", "Yellow", "Green", "Purple"], prompt: 'Select color' %>
    <%= f.input :description, label: false, placeholder: 'Please describe your suit' %>
    <%= f.input :style, label: false, collection: ["Classic suit", "Elegant tuxedo", "Eccentic suit"], prompt: 'Select style' %>
    <div class="sizes">
      <%= f.input :size, label: false, as: :radio_buttons, collection: ['XS', 'S', 'M', 'L', 'XL'] %>
    </div>
    <%= f.input :price_per_day, label: false, placeholder: 'Price / day' %>
    <%= f.input :address, label: false %>
    <%= f.input :photo, label: 'Photo:'%>
    <%= f.input :photo_cache, as: :hidden %>
    <div class="text-center" style= "padding-top: 10px;">
      <%= f.submit "Submit", class: "btn yellow-btn" %>
    </div>
  <% end %>
</div>

app/views/suits/_formrenting.html.erb
<div id="renting-form-div" data-rentings="<%= @rentings_dates.to_json %>">
  <%= simple_form_for [@suit, @renting], html: { class: "" } do |f| %>
    <%= f.input :start_date, as: :string, input_html: {class: "datepicker date-holder"}, label:false %>
    <%= f.input :end_date, as: :string, input_html: {class: "datepicker date-holder"}, label:false %>
    <div class="text-center" style="padding-top: 10px;">
      <%= f.submit "Reserve this suit", class: "btn yellow-btn" %>
    </div>
  <% end %>
</div>

app/views/suits/_map_box.html.erb
<div class="info-window">
  <h1 style="margin:1px; padding: 4px 0px; font-size: 16px;"><%= suit.name %></h1>
  <p style="margin-bottom:3px;"><%= suit.address.split.last(2).join(' ') %></p>
</div>

app/views/suits/edit.html.erb
<!-- <div class="new-wrapper" id="background-image-new" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://res.cloudinary.com/dnddzhvyj/image/upload/v1534845337/suit-banner.jpg');"> -->
  <div class="container edit-suit-container flex-container">
    <div class="flex-item">
      <!-- <h3> Edit your suit </h3> -->
      <div>
        <%= render 'form_suit' %>
      </div>
      <!-- <div id="bouton-back"> -->
        <%#= link_to "Back", suits_path, class: 'btn btn-primary' %>
      <!-- </div> -->
    </div>
  </div>
<!-- </div> -->

app/views/suits/index.html.erb
<div class="main-container">

  <div class="container" style="margin: 35px 20px 35px 0px;">
    <div class="row">
      <% @suits.each do |suit| %>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4" style="margin-bottom: 10px;">
        <div class="wrapper">
          <div class="card-container">
            <% if suit.photo.url.nil? %>
              <% url2 = cl_image_path('placeholder090821.png') %>
            <% else %>
              <% url2 = cl_image_path suit.photo %>
            <% end %>
            <div class="top" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= url2 %>');"></div>
            <div class="bottom">
              <h1><%= suit.name %></h1>
              <div style="display: flex; justify-content: space-between;">
                <p style="flex-grow: 1;"><%= suit.style %></p>
                <p style="padding-right: 6px;"><%= suit.reviews.count %> reviews</p>
                <p style="font-size: 12px;">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="far fa-star"></i>
                  <i class="far fa-star"></i>
                </p>
              </div>
            </div>
          </div>
          <% if suit.user.photo.url.nil? %>
            <%= cl_image_tag("vh5z2ujeausr6hlxy3zf", width: 80, height: 80, crop: :thumb, gravity: :face, class: 'card-avatar') %>
          <% else %>
            <%= cl_image_tag suit.user.photo, width: 80, height: 80, crop: :thumb, gravity: :face, class: 'card-avatar' %>
          <% end %>
          <p class="card-price">£ <%= suit.price_per_day %></p>
          <%= link_to suit_path(suit), class: 'card-link' do %><% end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <div class="map-container">
  <!-- <div class="search search-bar search-bar-index" style="margin: 0 0 35px 0;"> -->
    <div style="margin: 0 0 30px 0; font-size: 16px;">
      <%= form_tag suits_path, method: :get, class: 'suit-filter' do %>
        <%= select "color", "color_selector", ["Blue", "Black", "Red", "Yellow", "Green", "Purple"], include_blank: "Color" %>
        <%= select "style", "style_selector", ["Classic suit", "Elegant tuxedo", "Eccentic suit"], include_blank: "Style" %>
        <%= select "size", "size_selector", ["XS", "S", "M", "L", "XL"], include_blank: "Size" %>
        <%= submit_tag "Filter", :id => "submit-btn" %>
      <% end %>
    </div>

    <div id="map" data-markers="<%= @markers.to_json %>"></div>
  </div>

</div>

<script src='https://code.jquery.com/jquery-2.2.4.min.js'></script>

app/views/suits/new.html.erb
<div class="flex-container new-suit-background-image">
  <div class="flex-item" style="width: 34%;">
    <!-- <h3> Add a suit </h3> -->
    <div>
      <%= render 'form_suit' %>
    </div>
    <!-- <div id="bouton-back"> -->
      <%#= link_to "Back", suits_path, class: 'btn btn-primary' %>
    <!-- </div> -->
  </div>
</div>

app/views/suits/owner_index.html.erb
<div class="container" style="margin-top: 35px;">

  <h1 class="text-center">MY SUITS</h1>

  <div class="container" style="padding-top: 20px; padding-bottom: 70px; display: flex; justify-content: center;">
    <div style="display: flex;">
      <% @suits.each do |suit| %>
      <div>
        <div class="wrapper">
          <div class="card-container">
            <% if suit.photo.url.nil? %>
              <% url2 = cl_image_path('placeholder090821.png') %>
            <% else %>
              <% url2 = cl_image_path suit.photo %>
            <% end %>
            <div class="top" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= url2 %>');"></div>
            <div class="bottom">
              <h1><%= suit.name %></h1>
              <div style="display: flex; justify-content: space-between;">
                <p style="flex-grow: 1;"><%= suit.style %></p>
                <p style="padding-right: 6px;"><%= suit.reviews.count %> reviews</p>
                <p style="font-size: 12px;">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="far fa-star"></i>
                  <i class="far fa-star"></i>
                </p>
              </div>
            </div>
          </div>
          <% if suit.user.photo.url.nil? %>
            <%= cl_image_tag("vh5z2ujeausr6hlxy3zf", width: 80, height: 80, crop: :thumb, gravity: :face, class: 'card-user') %>
          <% else %>
            <%= cl_image_tag suit.user.photo, width: 80, height: 80, crop: :thumb, gravity: :face, class: 'card-user' %>
          <% end %>
          <p class="card-price"><%= suit.price_per_day %> €</p>
          <%= link_to suit_path(suit), class: 'card-link' do %><% end %>
        </div>
        <div class="text-center">
          <% if policy(suit).edit? %>
            <%= link_to edit_suit_path(suit), class: "btn btn-link" do %>
            <i class="fas fa-edit" style="font-size: 24px; color:gray;"></i><% end %>
          <% end %>
          <% if policy(suit).destroy? %>
            <%= link_to suit_path(suit),
                method: :delete,
                data: { confirm: "Delete this suit?" }, class: "btn btn-link" do %>
                <i class="far fa-trash-alt" style="font-size: 24px; color:gray;"></i><% end %>
          <% end %>
        </div>
      </div>
      <% end %>

      <div class="blank-photo" style="margin-top: 0;">+
        <%= link_to new_suit_path, class: 'card-link' do %><% end %>
      </div>

    </div>
  </div>
</div>

app/views/suits/show.html.erb
<div class="container" style="margin-top: 40px; margin-bottom: 25px;">

  <div style="display:flex;">

    <div class="show-image">
      <div class="card-container">
        <% if @suit.photo.url.nil? %>
          <% url2 = cl_image_path('placeholder090821.png') %>
        <% else %>
          <% url2 = cl_image_path @suit.photo %>
        <% end %>
        <div class="top" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= url2 %>');">
        </div>
      </div>
    </div>
    <div class="description-container" style="flex-grow: 1;">
      <h1 style="margin: 0; text-transform: uppercase;"><%= @suit.name %></h1>
      <div style="display: flex; align-items: center;">
        <div>
          <% if @suit.user.photo.url.nil? %>
            <%= cl_image_tag("vh5z2ujeausr6hlxy3zf", width: 80, height: 80, crop: :thumb, gravity: :face, style: 'border-radius: 50px; width: 40px; height: 40px;') %>
          <% else %>
            <%= cl_image_tag @suit.user.photo, width: 80, height: 80, crop: :thumb, gravity: :face, style: 'border-radius: 50px; width: 40px; height: 40px;' %>
          <% end %>
        </div>
        <div style="padding-left: 15px;">
          <h3>By
            <a href="#">
              <%= User.find(@suit.user_id).first_name %> <%= User.find(@suit.user_id).last_name %>
            </a>
          </h3>
        </div>
      </div>
      <br>
      <p>£<%= @suit.price_per_day %> / day</p>
      <p style="font-weight: lighter;">Size: <%= @suit.size %></p>
      <p class="dot" style="background-color: <%= @suit.color.downcase %>;"></p>
      <br>
      <br>
      <div style="font-weight: lighter; font-size: 17px;">
        <p>Tuxedo is 100% super-fine Italian merino wool</p>
        <p>Jacket has One-button closure</p>
        <p>Jacket has 100% silk satin shawl collar</p>
        <p>This complete outfit includes 6 items</p>
      </div>
    </div>

    <div style="padding-top: 10px;">
      <%= render 'formrenting', renting: @renting %>
    </div>

  </div>

  <div style="padding: 10px 70px;">
    <h3 style="color: black; margin-bottom: 20px;">Reviews</h3>
    <% @reviews.each do |review| %>
      <% if Renting.find(review.renting_id).suit_id == @suit.id %>
        <% User.find(review.user_id).first_name %> <% User.find(review.user_id).last_name %>
        <p><%= review.title %>
          <% review.rate.to_i.times do %>
            <i class="fas fa-star" style="font-size: 12px;"></i>
          <% end %>
          <% (5 - review.rate.to_i).times do %>
            <i class="far fa-star" style="font-size: 12px;"></i>
          <% end %>
        </p>
        <p style="font-weight: lighter"><%= review.content %></p>
      <% end %>
    <% end %>
  </div>

</div>

<div class="container" style="padding: 0 85px; margin-bottom: 75px;">
  <div id="map" style="width: 100%; height: 600px; margin-top: 0;" data-markers="<%= @markers.to_json %>">
  </div>
</div>