config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/suits/owner', to: 'suits#owner_index', as: 'owner_index'

  resources :suits do
    resources :rentings, only: [:create]
  end

  resources :rentings, only: [:index, :show, :destroy, :update] do
    resources :reviews, only: [:create]
    resources :messages, only:[:create, :show]
  end

  resources :reviews, only: [:show, :destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links" style="padding-bottom: 5px;">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook-f"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Made with <i class="fa fa-heart"></i> at Le Wagon by order of the Peaky Blinders.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right">

    <% if user_signed_in? %>

      <!-- Links when logged in -->

      <%= link_to "MY SUITS", owner_index_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "MY RENTINGS", rentings_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <div> <a href="/suits" class="btn btn-sm animated-button thar-three">Rent a suit now</a> </div>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.photo.url.nil? %>
            <%= cl_image_tag("tzcn9jxryoawvskg0s80.png", crop: :fill, class: "avatar dropdown-expand", id: "navbar-wagon-menu", "data-toggle" => "dropdown") %>
          <% else %>
            <%= cl_image_tag current_user.photo, height: 200, width: 200, crop: :fill, class: "avatar dropdown-expand", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-cog"></i>
                <%= t(".settings", default: "Edit profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i>
                <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>

      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <div> <a href="/suits" class="btn btn-sm animated-button thar-three">Rent a suit now</a> </div>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <!-- <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-expand" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div> -->
</div>