config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/suits/owner', to: 'suits#owner_index', as: 'owner_index'

  resources :suits do
    resources :rentings, only: [:create]
  end

  resources :rentings, only: [:index, :show, :destroy, :update] do
    resources :reviews, only: [:create]
    resources :messages, only:[:create, :show]
  end

  resources :reviews, only: [:show, :destroy]
end

app/models/renting.rb
class Renting < ApplicationRecord
  belongs_to :user
  belongs_to :suit
  has_many :reviews, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :user_id, presence: true
  validates :suit_id, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/controllers/rentings_controller.rb
class RentingsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_renting, only: [:show, :destroy, :update]

  def index
    @rentings = policy_scope(Renting).where(user_id: current_user).order(id: :desc)
    @owner_suits = policy_scope(Suit).where(user_id: current_user)
  end

  def create
    @suit = Suit.find(params[:suit_id])
    @renting = Renting.new(renting_params)
    @renting.user_id = current_user.id
    @renting.suit_id = @suit.id
    authorize @renting

    if @renting.save
      redirect_to rentings_path
    else
      render './suits/show'
    end
  end

  def show
    authorize @renting
    @suit = @renting.suit
    @owner = @renting.suit.user
    @review = Review.new
    @message = Message.new
    @messages = Message.where(renting_id: params[:id]).reverse_order
  end

  def update
    @renting.pending = false
    authorize @renting
    @renting.save
    redirect_to rentings_path
  end

  def destroy
    authorize @renting
    @renting.destroy!
    @suit = Suit.find(@renting.suit_id)
    if current_user == @suit.user
      redirect_to rentings_path
    else
    redirect_to suit_path(@suit)
    end
  end

  private

  def renting_params
    params.require(:renting).permit(:start_date, :end_date, :pending)
  end

  def set_renting
    @renting = Renting.find(params[:id])
  end


end

app/views/rentings/_formmessage.html.erb
 <!--  <p> Rent this awesome suit </p> -->

app/views/rentings/_formreview.html.erb
  <h1 class="flex-item">Rate your order</h1>
  <div id="renting-form-div flex-item">
    <%= simple_form_for [@renting, @review] do |f| %>
        <%= f.input :title, label:'Title' %>
        <%= f.input :rate, label:'Rate', as: :hidden %>
        <fieldset class="rating">
          <input type="radio" id="star5" name="rating" value="5" /><label class = "full star-rate" for="star5" title="Awesome - 5 stars"></label>
          <input type="radio" id="star4" name="rating" value="4" /><label class = "full star-rate" for="star4" title="Pretty good - 4 stars"></label>
          <input type="radio" id="star3" name="rating" value="3" /><label class = "full star-rate" for="star3" title="Meh - 3 stars"></label>
          <input type="radio" id="star2" name="rating" value="2" /><label class = "full star-rate" for="star2" title="Kinda bad - 2 stars"></label>
          <input type="radio" id="star1" name="rating" value="1" /><label class = "full star-rate" for="star1" title="Sucks big time - 1 star"></label>
        </fieldset>
        <%= f.input :content, label:'Message and rate' %>
        <div class="text-center">
        <%= f.submit "Leave a review", class: "btn yellow-btn" %>
        </div>
    <% end %>
  </div>

app/views/rentings/_history_owner.html.erb
<div class="container" style="margin-top: 30px;">
  <% if @owner_suits.first.nil? %>
    <p>You don't have any suit on the platform</p>
  <% else %>
    <!-- <h1 class="project-name">My rentings timeline</h1> -->
      <div id="timeline">
        <% @owner_suits.each do |suit| %>
          <% suit.rentings.order(id: :desc).where(pending: true).each do |renting| %>
          <div class="timeline-item">
            <div class="timeline-icon">
              <svg version="1.1" id="Layer_1" x="0px" y="0px"
               width="21px" height="20px" viewBox="0 0 21 20" enable-background="new 0 0 21 20" xml:space="preserve">
              <path fill="#FFFFFF" d="M19.998,6.766l-5.759-0.544c-0.362-0.032-0.676-0.264-0.822-0.61l-2.064-4.999
                c-0.329-0.825-1.5-0.825-1.83,0L7.476,5.611c-0.132,0.346-0.462,0.578-0.824,0.61L0.894,6.766C0.035,6.848-0.312,7.921,0.333,8.499
                l4.338,3.811c0.279,0.246,0.395,0.609,0.314,0.975l-1.304,5.345c-0.199,0.842,0.708,1.534,1.468,1.089l4.801-2.822
                c0.313-0.181,0.695-0.181,1.006,0l4.803,2.822c0.759,0.445,1.666-0.23,1.468-1.089l-1.288-5.345
                c-0.081-0.365,0.035-0.729,0.313-0.975l4.34-3.811C21.219,7.921,20.855,6.848,19.998,6.766z"/>
              </svg>
            </div>
            <div class="timeline-content right">
              <div class="row">
                <div class="col-xs-9">
                  <h2>Suit rented to: <strong><%= renting.user.first_name %> <%= renting.user.last_name %></strong></h2>
                  <div class="timeline-description">
                    <p style="padding-top: 10px">
                      Start date: <%= renting.start_date %>
                      -
                      End date: <%= renting.end_date %>
                    </p>
                    <%= link_to "View my renting", renting_path(renting.id), class: 'yellow-btn'%>
                  </div>
                </div>
                <div class="col-xs-3">
                  <% if renting.suit.photo.url.nil? %>
                    <% url2 = cl_image_tag('placeholder090821.png',
            width: 150, height: 200, crop: :fill) %>
                  <% else %>
                    <% url2 = cl_image_tag(renting.suit.photo,
            width: 160, height: 220, crop: :fill) %>
                  <% end %>
                <%= url2 %>
                </div>
              </div>
            </div>
            <div class="timeline-validation">
              <h4>Accept this renting?</h4>
              <%= link_to renting_path(renting), method: :patch do %>
                <i class="yellow-btn">Accept</i>
              <% end %>
              <%= link_to renting_path(renting), method: :delete do %>
                <i class="grey-btn">Refuse</i>
              <% end %>
            </div>
          </div>
          <% end %>
        <h2>Accepted rentings</h2>
          <% suit.rentings.order(id: :desc).where(pending: false).each do |renting| %>
          <div class="timeline-item">
            <div class="timeline-icon">
              <svg version="1.1" id="Layer_1" x="0px" y="0px"
               width="21px" height="20px" viewBox="0 0 21 20" enable-background="new 0 0 21 20" xml:space="preserve">
              <path fill="#FFFFFF" d="M19.998,6.766l-5.759-0.544c-0.362-0.032-0.676-0.264-0.822-0.61l-2.064-4.999
                c-0.329-0.825-1.5-0.825-1.83,0L7.476,5.611c-0.132,0.346-0.462,0.578-0.824,0.61L0.894,6.766C0.035,6.848-0.312,7.921,0.333,8.499
                l4.338,3.811c0.279,0.246,0.395,0.609,0.314,0.975l-1.304,5.345c-0.199,0.842,0.708,1.534,1.468,1.089l4.801-2.822
                c0.313-0.181,0.695-0.181,1.006,0l4.803,2.822c0.759,0.445,1.666-0.23,1.468-1.089l-1.288-5.345
                c-0.081-0.365,0.035-0.729,0.313-0.975l4.34-3.811C21.219,7.921,20.855,6.848,19.998,6.766z"/>
              </svg>
            </div>
            <div class="timeline-content right">
              <div class="row">
                <div class="col-xs-9">
                  <h2>Suit rented to: <strong><%= renting.user.first_name %> <%= renting.user.last_name %></strong></h2>
                  <div class="timeline-description">
                    <p style="padding-top: 10px">
                      Start date: <%= renting.start_date %>
                      -
                      End date: <%= renting.end_date %>
                    </p>
                    <%= link_to "View my renting", renting_path(renting.id), class: 'yellow-btn'%>
                  </div>
                </div>
                <div class="col-xs-3">
                  <% if renting.suit.photo.url.nil? %>
                    <% url2 = cl_image_tag('placeholder090821.png',
            width: 150, height: 200, crop: :fill) %>
                  <% else %>
                    <% url2 = cl_image_tag(renting.suit.photo,
            width: 160, height: 220, crop: :fill) %>
                  <% end %>
                <%= url2 %>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        <% end %>
      </div>
  <% end %>
</div>

app/views/rentings/_history_renter.html.erb
<!-- <h1 class="project-name">My rentings timeline</h1> -->
<div class="container" style="margin-top: 30px;">
  <div id="timeline">
    <% @rentings.each do |renting| %>
      <div class="timeline-item">
        <div class="timeline-icon">
          <svg version="1.1" id="Layer_1" x="0px" y="0px"
           width="21px" height="20px" viewBox="0 0 21 20" enable-background="new 0 0 21 20" xml:space="preserve">
          <path fill="#FFFFFF" d="M19.998,6.766l-5.759-0.544c-0.362-0.032-0.676-0.264-0.822-0.61l-2.064-4.999
            c-0.329-0.825-1.5-0.825-1.83,0L7.476,5.611c-0.132,0.346-0.462,0.578-0.824,0.61L0.894,6.766C0.035,6.848-0.312,7.921,0.333,8.499
            l4.338,3.811c0.279,0.246,0.395,0.609,0.314,0.975l-1.304,5.345c-0.199,0.842,0.708,1.534,1.468,1.089l4.801-2.822
            c0.313-0.181,0.695-0.181,1.006,0l4.803,2.822c0.759,0.445,1.666-0.23,1.468-1.089l-1.288-5.345
            c-0.081-0.365,0.035-0.729,0.313-0.975l4.34-3.811C21.219,7.921,20.855,6.848,19.998,6.766z"/>
          </svg>
        </div>
        <div class="timeline-content right">
          <div class="row">
            <div class="col-xs-9">
              <h2>Suit rented: <strong><%= Suit.find(renting.suit_id).name %></strong></h2>
              <div class="timeline-description">
                <h3>Rented from: <%= renting.suit.user.first_name %> <%= renting.suit.user.last_name %></h3>
                <p>
                  Start date: <%= renting.start_date %>
                  -
                  End date: <%= renting.end_date %>
                </p>
                <%= link_to "View my renting", renting_path(renting.id), class: 'yellow-btn'%>
              </div>
            </div>
            <div class="col-xs-3">
              <% if renting.suit.photo.url.nil? %>
                <% url2 = cl_image_tag('placeholder090821.png',
        width: 150, height: 200, crop: :fill) %>
              <% else %>
                <% url2 = cl_image_tag(renting.suit.photo,
        width: 160, height: 220, crop: :fill) %>
              <% end %>
            <%= url2 %>
            </div>
          </div>
        </div>
        <div class="timeline-waitingvalidation">
            <h4>Owner info</h4>
            <p>
              Email: <strong><%= renting.suit.user.email %></strong>
            </p>
            <p>
              Phone number: <strong><%= renting.suit.user.phone %></strong>
            </p>
            <% if renting.pending %>
              <p style="color: orange"><i class="fas fa-exclamation-triangle"></i> Waiting owner validation</p>
            <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/rentings/index.html.erb
<div class="container rentings-container">
  <!-- Nav tabs -->
  <ul class="nav nav-tabs timeline-nav-flex" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab" class="yellow-background" data-name="renter">My rentings history</a></li>
    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab" data-name="owner">My owner history</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="home"> <%= render 'history_renter' %> </div>
    <div role="tabpanel" class="tab-pane" id="profile"> <%= render 'history_owner' %> </div>
  </div>
</div>

app/views/rentings/show.html.erb
<div class="wrapper-show-renting">
  <div class="container">

      <div class="row">
        <div class="col-xs-3 col-xs-offset-1">
          <%= cl_image_tag(@renting.suit.photo, width: 200, height: 300, crop: :fill) %>
        </div>
        <div class="col-xs-7">
          <div class="order-recap">
            <h1>Order Recap</h1>
            <p>Nom du costume: <strong><%= @suit.name %></strong></p>
            <p>Propriétaire: <strong><%= @owner.first_name %> <%= @owner.last_name%></strong></p>
            <p>Numéro de téléphone: <strong><%= @owner.phone %></strong></p>
            <p>Email: <strong><%= @owner.email %></strong></p>
            <p>Dates de réservation: <strong><%= @renting.start_date %></strong> - <strong><%= @renting.end_date %></strong></p>
            <p>Prix: <strong><%= @suit.price_per_day * (@renting.end_date - @renting.start_date).numerator %> €</strong></p>
          </div>
        </div>
      </div>

    <div class="order-review-and-chat">
        <%= render 'formreview', review: @review %>

    </div>

    <div class="chat-container">
      <div class="chat-wrapper flex-item">
        <h1><strong>CHAT</strong></h1>

        <div id="messages">
          <% @messages.order(id: :desc).each do |message| %>
            <%= render 'messages/show', message: message %>
          <% end %>
        </div>

        <div id="renting-form-div" class="text-center">
          <%= render 'messages/form', renting: @renting, message: @message %>
        </div>
      </div>
    </div>

  </div>
</div>